version: '3.3'

services:
  minid-updater:
    image: ${REGISTRY}/minid-updater:${VERSION}
    configs:
      - log_config
    extra_hosts:
      - "eid-elk-app01.dmz.local:10.243.220.21"
    ports:
      - 8080
    networks:
      atest:
    dns: 8.8.8.8
    deploy:
      placement:
        constraints:
          - node.labels.atest == true
  idporten-admin:
    image: eid-jenkins02.dmz.local:8081/idporten-admin:latest
    extra_hosts:
      - "eid-elk-app01.dmz.local:10.243.220.21"
    configs:
      - log_config
    ports:
      - 8080
    networks:
      atest:
    dns: 8.8.8.8
    deploy:
      placement:
        constraints:
          - node.labels.atest == true
  idporten-oidc-provider:
    image: eid-jenkins02.dmz.local:8081/idporten-oidc-provider:latest
    configs:
      - log_config
    extra_hosts:
      - "eid-elk-app01.dmz.local:10.243.220.21"
    ports:
      - 8080
    networks:
      atest:
    dns: 8.8.8.8
    deploy:
      placement:
        constraints:
          - node.labels.atest == true
  activemq:
    image:  rmohr/activemq:5.11.1
    extra_hosts:
      - "eid-elk-app01.dmz.local:10.243.220.21"
    configs:
      - log_config
    ports:
      - 61616
      - 8161
    networks:
      atest:
    dns: 8.8.8.8
    deploy:
      placement:
        constraints:
          - node.labels.atest == true
  eventlog-db:
    image: eid-jenkins02.dmz.local:8081/eventlog-db:latest
    ports:
      - 3306
    extra_hosts:
      - "eid-elk-app01.dmz.local:10.243.220.21"
    networks:
      atest:
    dns: 8.8.8.8
    deploy:
      placement:
        constraints:
          - node.labels.atest == true
  kontaktregister-db:
    image: eid-jenkins02.dmz.local:8081/kontaktregister-db:latest
    ports:
      - 3306
    networks:
      atest:
    dns: 8.8.8.8
    deploy:
      placement:
        constraints:
          - node.labels.atest == true
  oidc-db:
    image: eid-jenkins02.dmz.local:8081/oidc-db:latest
    ports:
      - 3306
    extra_hosts:
      - "eid-elk-app01.dmz.local:10.243.220.21"
    networks:
      atest:
    dns: 8.8.8.8
    command: --sql_mode=""
    deploy:
      placement:
        constraints:
          - node.labels.atest == true
  testsp-saml:
    image:  eid-jenkins02.dmz.local:8081/testsp-saml:latest
    extra_hosts:
      - "eid-elk-app01.dmz.local:10.243.220.21"
    configs:
      - log_config
    ports:
      - 8080
    networks:
      atest:
    dns: 8.8.8.8
    deploy:
      placement:
        constraints:
          - node.labels.atest == true
  kontaktinfo-backend:
    image:  eid-jenkins02.dmz.local:8081/kontaktinfo-backend:latest
    extra_hosts:
      - "eid-elk-app01.dmz.local:10.243.220.21"
    configs:
      - log_config
    ports:
      - 8080
    networks:
      atest:
    dns: 8.8.8.8
    deploy:
      placement:
        constraints:
          - node.labels.atest == true
  opendj:
    image: eid-jenkins02.dmz.local:8081/opendj:latest
    extra_hosts:
      - "eid-elk-app01.dmz.local:10.243.220.21"
    configs:
      - log_config
    networks:
      atest:
    dns: 8.8.8.8
    deploy:
      placement:
        constraints:
          - node.labels.atest == true
  web:
    image: eid-jenkins02.dmz.local:8081/web:latest
    extra_hosts:
      - "eid-elk-app01.dmz.local:10.243.220.21"
    configs:
      - log_config
    ports:
      - 443
    networks:
      atest:
        aliases:
          - eid-atest-web01.dmz.local
          - eid-inttest-web01.dmz.local
    dns: 8.8.8.8
    deploy:
      placement:
        constraints:
          - node.labels.atest == true
  serviceprovider-backend:
    image: eid-jenkins02.dmz.local:8081/serviceprovider-backend:latest
    configs:
      - log_config
    extra_hosts:
      - "eid-elk-app01.dmz.local:10.243.220.21"
    ports:
      - 8080
    networks:
      atest:
    dns: 8.8.8.8
    deploy:
      placement:
        constraints:
          - node.labels.atest == true
  idporten-openam:
    image: eid-jenkins02.dmz.local:8081/idporten-openam:latest
    extra_hosts:
      - "eid-elk-app01.dmz.local:10.243.220.21"
    configs:
      - log_config
    ports:
      - 8080
    networks:
      atest:
    dns: 8.8.8.8
    deploy:
      placement:
        constraints:
          - node.labels.atest == true
  logwriter:
    image:  eid-jenkins02.dmz.local:8081/logwriter:latest
    extra_hosts:
      - "eid-elk-app01.dmz.local:10.243.220.21"
    configs:
      - log_config
    networks:
      atest:
    dns: 8.8.8.8
    deploy:
      placement:
        constraints:
          - node.labels.atest == true
  selenium:
    image: selenium/standalone-chrome-debug:3.14.0-europium
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - 4444
    networks:
      atest:
        aliases:
          - selenium_host
    dns: 8.8.8.8
    deploy:
      placement:
        constraints:
          - node.labels.atest == true
  kontaktinfo-backend-gateway-with-postbox-mock:
    image:  eid-jenkins02.dmz.local:8081/kontaktinfo-backend-gateway-with-postbox-mock:latest
    extra_hosts:
      - "eid-elk-app01.dmz.local:10.243.220.21"
    configs:
      - log_config
    ports:
      - 8080
    networks:
      atest:
    dns: 8.8.8.8
    deploy:
      placement:
        constraints:
          - node.labels.atest == true
networks:
  atest:
    driver: overlay
    attachable: true
configs:
  log_config:
    file: ./log_config